//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClasswiseSyllabu
    {
        public tblClasswiseSyllabu()
        {
            this.tblClasswiseSyllabus_Records = new HashSet<tblClasswiseSyllabus_Records>();
        }
    
        public int RecordId { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate_utc { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDate { get; set; }
        public string Assessment_Year_Desc { get; set; }
        public Nullable<bool> Record_Status { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> School_Id { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<bool> Manually_added { get; set; }
    
        public virtual ICollection<tblClasswiseSyllabus_Records> tblClasswiseSyllabus_Records { get; set; }
    }
}
