//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClassSectionTimeTable_Records
    {
        public int RecordId { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate_utc { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDate { get; set; }
        public Nullable<bool> Record_Status { get; set; }
        public Nullable<int> TimeTable_RecordId { get; set; }
        public Nullable<System.TimeSpan> Period_Start { get; set; }
        public Nullable<System.TimeSpan> Period_end { get; set; }
        public Nullable<short> Period_Order { get; set; }
        public Nullable<int> Period_Day { get; set; }
        public string Subject_Id { get; set; }
        public string Subject_Desc { get; set; }
    
        public virtual tblBaseWeekDay tblBaseWeekDay { get; set; }
        public virtual tblClassSectionTimeTable tblClassSectionTimeTable { get; set; }
    }
}
