//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClasswiseSyllabus_Records
    {
        public int RecordId { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate_utc { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDate { get; set; }
        public string Assessment_Year_Desc { get; set; }
        public Nullable<bool> Record_Status { get; set; }
        public Nullable<int> Syllabus_RecordId { get; set; }
        public string Topic_Name { get; set; }
        public Nullable<short> Topic_Order { get; set; }
        public Nullable<bool> Header { get; set; }
        public Nullable<bool> sub_header { get; set; }
        public Nullable<bool> sub1_header { get; set; }
        public Nullable<bool> sub2_header { get; set; }
        public Nullable<bool> sub3_header { get; set; }
        public Nullable<bool> sub4_header { get; set; }
        public Nullable<bool> sub5_header { get; set; }
    
        public virtual tblClasswiseSyllabu tblClasswiseSyllabu { get; set; }
    }
}
