//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffDetail
    {
        public int RecordId { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate_utc { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDate { get; set; }
        public Nullable<bool> Record_Status { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string Ph_No { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string BloodGroup { get; set; }
        public string knownlanguages { get; set; }
        public string Photo { get; set; }
        public string Highest_degree { get; set; }
        public string Specialization { get; set; }
        public string Additional_Degree { get; set; }
        public string Addition_Degree_Special { get; set; }
        public string Subject1 { get; set; }
        public string Subject2 { get; set; }
        public string Subject3 { get; set; }
        public string Subject4 { get; set; }
        public string Subject5 { get; set; }
        public string Prev_Org { get; set; }
        public Nullable<short> Prev_Org_Exp_yrs { get; set; }
        public Nullable<short> Prev_Org_Exp_Mnths { get; set; }
        public string Prev_Org_Designation { get; set; }
        public Nullable<int> Prev_Salary { get; set; }
        public Nullable<short> Overall_Prev_Exp_yrs { get; set; }
        public Nullable<short> Overall_Prev_Exp_Mnths { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Hod_Dept { get; set; }
        public Nullable<int> Sal_Per_Month { get; set; }
        public Nullable<int> CTC { get; set; }
    }
}
