//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public tblStudentDetail()
        {
            this.tblParentDetails = new HashSet<tblParentDetail>();
        }
    
        public int RecordId { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate_utc { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDate { get; set; }
        public Nullable<bool> Record_Status { get; set; }
        public string Std_FName { get; set; }
        public string Std_LName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Gender { get; set; }
        public string Blood_Group { get; set; }
        public string photo_url { get; set; }
        public string Ph_No { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public Nullable<int> State_ID { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Mole1 { get; set; }
        public string Mole2 { get; set; }
        public string Mole3 { get; set; }
        public string Mole4 { get; set; }
        public string Mole5 { get; set; }
        public string Joined_Assessment_Year { get; set; }
        public string Prev_Class { get; set; }
        public string Prev_School { get; set; }
        public string Prev_Class_Percentage { get; set; }
        public string Scholar_Type { get; set; }
        public string Joining_Class { get; set; }
        public string Present_Class { get; set; }
        public string Medium_Type { get; set; }
        public string Referral_Lecturer { get; set; }
        public Nullable<int> Lecturer_Id { get; set; }
        public string Assigned_Coordinator { get; set; }
        public Nullable<int> Assigned_Coordinator_Id { get; set; }
    
        public virtual ICollection<tblParentDetail> tblParentDetails { get; set; }
    }
}
